### PR TITLE
Add reuse compliance

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* SPDX header
* CI action
* Readme badge
* Code owner file

### CODE REVIEW

**Review by kyteinsky — COMMENTED** [review]
For python files, it is better to use triple quotes
```
"""
SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
SPDX-License-Identifier: AGPL-3.0-or-later
"""
```

**Comment by DaphneMuller** [comment]
@kyteinsky please directly fix it yourself and merge! that would be faster

**Comment by AndyScherzinger** [comment]
We always used the pound.-key, see https://github.com/search?q=org%3Anextcloud+SPDX+language%3APython+&type=code but feel free to use the triple quotes

**Comment by kyteinsky** [comment]
Oh it's all good then. We don't have module-level comments here anyway so no consistency issues.

**Review by kyteinsky — APPROVED** [review]

**Pull request merged**
